### ISSUE TITLE
Calculation error

### ISSUE THREAD

**Issue by laryn** [progressivetech/net.ourpowerbase.sumfields#49] opened 2019-03-11 19:53 UTC
I'm running into something that seems like a bug. I've disabled/uninstalled and then reinstalled and see the same thing.

The situation is this:

 - An event with registration has line items (e.g. meal selections) that have separate payment amounts.
 - Registrants have the option to register/pay for more than one person.

The outcome:

 - Summary field calculations seem to take the quantity of line items or registrations and multiply the total amount by that. So if the final fee is $150 and is made up of $100 event fee plus $50 meal fee (2 line items), the summary is showing up as $300 (the total $150 multiplied by the number of line items).

Likewise if someone registers two people for basic registration ($100 for one, $100 for the other) we're seeing the summary field show $400 as the summary amount rather than $200.

**Comment by jmcclelland** [comment] 2019-03-11 20:02
This latest version made a change that affected how quantities are calculated which may be contributing to this bug. I haven't yet confirmed.

**Comment by eileenmcnaughton** [comment] 2019-04-26 11:27
@jmcclelland I CAN confirm this commit https://github.com/progressivetech/net.ourpowerbase.sumfields/commit/28afbe40d21dcf8d05f1959cb8f826d575df360f is doing VERY bad things to the totals :-(

We have lots of contacts being acknowledged for their gifts & it turns out that as they have 2 line items - one of $0 value - we were about to acknowledge them for double their donations!

I think switching to line_total instead of total_amount in this line will work -

.sumfields/commit/28afbe40d21dcf8d05f1959cb8f826d575df360f#diff-2ed8b3d30faed4caf82736f4278b7cc0R105

**Comment by jmcclelland** [comment] 2019-09-13 16:55
Thanks again Eileen. Closing this out.

**Closed by jmcclelland** 2019-09-13 16:55 UTC
